spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource: 
    url: jdbc:mysql://localhost:3306/storeproject?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: bfeceb
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n/message